# Generated by Django 5.2 on 2025-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_lost', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('is_found', models.BooleanField(default=False)),
            ],
        ),
    ]
