# Generated by Django 5.2 on 2025-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_lostfounditem_delete_lostitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
