# Generated by Django 5.2 on 2025-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_alter_lostfounditem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
